apiVersion: connectorctl.io/v1alpha1
profiles:
  mounted-file:
    type: kubernetes-mounted-secret
    mountRoot: /mnt/secrets
    defaultFile: custom.properties
  existing-k8s:
    type: kubernetes-mounted-secret
    mountRoot: /mnt/secrets
    defaultFile: custom.properties
  vault-static:
    type: VaultStaticSecret
    mountRoot: /mnt/secrets
    defaultFile: custom.properties
  vault-db-static:
    type: VaultDynamicSecret-static-role
    mountRoot: /mnt/secrets
    defaultFile: custom.properties
  vault-db-dynamic:
    type: VaultDynamicSecret-dynamic-role
    mountRoot: /mnt/secrets
    defaultFile: custom.properties
security:
  neverPersistPlaintext: true
  neverLogSecretValues: true
